part1 :
	@g++ src/shared.cpp src/part1.cpp -o main -std=c++20 -lfmt -Wall

part2 :
	@g++ src/shared.cpp src/part2.cpp -o main -std=c++20 -lfmt -Wall

run :
	@cat input.txt | ./main

test : 
	@cat test.txt | ./main
